name: dospace
description: Client library to interact with the DigitalOcean Spaces API. Same API as Amazon AWS S3.
version: 0.12.14
homepage: https://github.com/nbspou/dospace
author: NO-BREAK SPACE OÜ <support@no-break.space>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  crypto: ^3.0.1
  http: ^0.13.3
  xml: ^5.1.1
  dio: ^4.0.4

dev_dependencies:
  test: ^1.17.11
  ini: ^2.1.0
